### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by NahuelMaSSaCre** [NahuelMaSSaCre/BTCF#7]
Deveriamos tratar de separar completamente el html del los estilos. 
Esto nos permitira trazabilidad para realizar cambios y mejorara la posibilidad
de que los usuarios del BTCF puedan realizar cambios esteticos sin perderse
en los archivos de template.

**Comment by nechuz** [comment]
Toda la razon, Yo me encargo de corregirlo

**Comment by nechuz** [comment]
Cambios finalizados. Ya se puede cerrar
